# Retorna a bibliografia de um único item no Wikidata
# Rodar o script em: https://query-scholarly.wikidata.org/

SELECT ?valor ?valorLabel WHERE {
  # 1. Retorna todos os valores (QIDs) da propriedade "cita" (P2860) no item Q*********
  wd:Q********* wdt:P2860 ?valor .
  
  # 2. Usa o serviço de rótulos para preencher ?valorLabel
  SERVICE wikibase:label {
    # Define a ordem de preferência de idiomas: Português, Múltiplos (padrão), e Inglês.
    # Se um rótulo existir em qualquer um desses, ele será retornado.
    bd:serviceParam wikibase:language "pt,pt-br,mul,en" .
  }
}
