# Etapa 1 - Coleta de dados
# Este script coleta a produção científica do NeuroMat. Deve ser rodada em https://query-scholarly.wikidata.org.
# Na presente metodologia, o resultado deve ser salvo com o título "df_wikidata.csv" no diretório /data/ da estrutura do Flask

#title: Scholarly articles from NeuroMat, retrieving labels and identifiers
SELECT ?item ?itemLabel ?doi ?isbn ?arxiv ?pmid WHERE {
{?item wdt:P361 wd:Q18477654.}
UNION
{
SERVICE wdsubgraph:wikidata_main {
SELECT ?item ?itemLabel ?doi ?isbn ?arxiv ?pmid WHERE {
?item wdt:P361 wd:Q18477654.
OPTIONAL {?item wdt:P356 ?doi.}
OPTIONAL {?item wdt:P212 ?isbn.}
OPTIONAL {?item wdt:P818 ?arxiv.}
OPTIONAL {?item wdt:P698 ?pmid.}
SERVICE wikibase:label { bd:serviceParam wikibase:language "pt-br, pt, en, es, fr, de, ja, mul". }
}
}
}
OPTIONAL {?item wdt:P356 ?doi.}
OPTIONAL {?item wdt:P212 ?isbn.}
OPTIONAL {?item wdt:P818 ?arxiv.}
OPTIONAL {?item wdt:P698 ?pmid.}
SERVICE wikibase:label { bd:serviceParam wikibase:language "pt-br, pt, en, es, fr, de, ja, mul". }
}

